import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { buildExpirationStats } from "@shared/expirationStats";
import { AlertTriangle, CalendarClock, CalendarDays, ChartNoAxesCombined, FileDown, FileText, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, ReferenceLine, Tooltip, XAxis, YAxis } from "recharts";

type Status = "pending" | "safe" | "urgent" | "overdue" | "stopped" | "paused";
type ProductSchedule = { id: number; name: string; parentTypeName?: string | null; intervalMonths: number; nextDeadline: string | null; daysRemaining: number | null; status: Status };
type Certificate = { id: number; productId: number | null; fileName: string; inspectionDate: string | null; downloadUrl: string };

const statusColor: Record<Status, string> = { overdue: "#dc2626", urgent: "#d97706", safe: "#059669", pending: "#64748b", stopped: "#94a3b8", paused: "#8b5cf6" };
const chartConfig = { daysRemaining: { label: "잔여 일수", color: "#0f766e" } } satisfies ChartConfig;
const riskChartConfig = { overdue: { label: "기간 초과", color: "#dc2626" }, critical: { label: "7일 이내", color: "#d97706" }, upcoming: { label: "8~30일", color: "#0f766e" } } satisfies ChartConfig;

function dateKey(date: Date) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Seoul", year: "numeric", month: "2-digit", day: "2-digit" }).format(date); }
function dateText(iso: string) { const [year, month, day] = iso.split("-"); return `${year}. ${Number(month)}. ${Number(day)}.`; }
function dDayText(days: number | null) { if (days === null) return "-"; if (days < 0) return `${Math.abs(days)}일 초과`; if (days === 0) return "오늘 마감"; return `D-${days}`; }
function statusBadgeClass(status: Status) { return status === "overdue" ? "border-red-200 bg-red-50 text-red-700" : status === "urgent" ? "border-amber-200 bg-amber-50 text-amber-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"; }

export default function InspectionInsights({ productSchedules, certificates, onGenerateMonthlyReport }: { productSchedules: ProductSchedule[]; certificates: Certificate[]; onGenerateMonthlyReport: () => void }) {
  const [selectedDate, setSelectedDate] = useState<Date | undefined>(new Date());
  const [detailOpen, setDetailOpen] = useState(false);
  const activeSchedules = useMemo(() => productSchedules.filter(item => item.nextDeadline && item.daysRemaining !== null && !["stopped", "paused", "pending"].includes(item.status)), [productSchedules]);
  const chartData = useMemo(() => [...activeSchedules].sort((a, b) => (a.daysRemaining ?? 9999) - (b.daysRemaining ?? 9999)).slice(0, 12).map(item => ({ ...item, label: item.name.length > 10 ? `${item.name.slice(0, 10)}…` : item.name })), [activeSchedules]);
  const dateGroups = useMemo(() => { const groups = new Map<string, ProductSchedule[]>(); activeSchedules.forEach(item => { const key = item.nextDeadline!; groups.set(key, [...(groups.get(key) ?? []), item]); }); return groups; }, [activeSchedules]);
  const datesByStatus = useMemo(() => ({ overdue: activeSchedules.filter(item => item.status === "overdue").map(item => new Date(`${item.nextDeadline}T12:00:00`)), urgent: activeSchedules.filter(item => item.status === "urgent").map(item => new Date(`${item.nextDeadline}T12:00:00`)), safe: activeSchedules.filter(item => item.status === "safe").map(item => new Date(`${item.nextDeadline}T12:00:00`)) }), [activeSchedules]);
  const selectedItems = selectedDate ? dateGroups.get(dateKey(selectedDate)) ?? [] : [];
  const certificatesByProduct = useMemo(() => { const grouped = new Map<number, Certificate[]>(); certificates.filter(item => item.productId).forEach(item => grouped.set(item.productId!, [...(grouped.get(item.productId!) ?? []), item])); return grouped; }, [certificates]);
  const excludedCount = productSchedules.length - activeSchedules.length;
  const expirationStats = useMemo(() => buildExpirationStats(activeSchedules), [activeSchedules]);
  const riskBuckets = useMemo(() => [{ label: "기간 초과", count: expirationStats.overdue, color: "#dc2626" }, { label: "7일 이내", count: expirationStats.critical, color: "#d97706" }, { label: "8~30일", count: expirationStats.upcoming, color: "#0f766e" }, { label: "31일 이후", count: expirationStats.later, color: "#64748b" }], [expirationStats]);

  return <section className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Card className="border-red-100 bg-red-50/60"><CardContent className="p-4"><div className="flex items-center justify-between text-red-700"><span className="text-xs font-bold">기간 초과</span><AlertTriangle className="h-4 w-4" /></div><p className="mt-2 text-3xl font-black text-red-800">{expirationStats.overdue}<span className="ml-1 text-sm font-semibold">건</span></p><p className="mt-1 text-[11px] text-red-700">즉시 검사 의뢰 대상</p></CardContent></Card>
      <Card className="border-amber-100 bg-amber-50/70"><CardContent className="p-4"><div className="flex items-center justify-between text-amber-700"><span className="text-xs font-bold">7일 이내 긴급</span><ShieldAlert className="h-4 w-4" /></div><p className="mt-2 text-3xl font-black text-amber-800">{expirationStats.critical}<span className="ml-1 text-sm font-semibold">건</span></p><p className="mt-1 text-[11px] text-amber-700">긴급 텔레그램 알림 대상</p></CardContent></Card>
      <Card className="border-teal-100 bg-teal-50/70"><CardContent className="p-4"><div className="flex items-center justify-between text-teal-700"><span className="text-xs font-bold">8~30일 내 마감</span><CalendarClock className="h-4 w-4" /></div><p className="mt-2 text-3xl font-black text-teal-800">{expirationStats.upcoming}<span className="ml-1 text-sm font-semibold">건</span></p><p className="mt-1 text-[11px] text-teal-700">사전 검사 계획 대상</p></CardContent></Card>
      <Card className="border-slate-200 bg-slate-50"><CardContent className="p-4"><div className="flex items-center justify-between text-slate-600"><span className="text-xs font-bold">관리 제품</span><ChartNoAxesCombined className="h-4 w-4" /></div><p className="mt-2 text-3xl font-black text-slate-800">{expirationStats.total}<span className="ml-1 text-sm font-semibold">건</span></p><p className="mt-1 text-[11px] text-slate-600">중단·중지·입력 대기 제외 {excludedCount}건</p></CardContent></Card>
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="border-border/80 shadow-sm"><CardHeader className="border-b bg-[linear-gradient(120deg,oklch(0.98_0.01_195),white)]"><CardTitle className="flex items-center gap-2 text-lg"><ChartNoAxesCombined className="h-5 w-5 text-primary" />제품별 검사 잔여일수</CardTitle><CardDescription>제품별 검사 주기와 최근 제조일을 기준으로, 마감이 가까운 순서로 비교합니다.</CardDescription></CardHeader><CardContent className="pt-5">{chartData.length ? <ChartContainer config={chartConfig} className="h-[280px] w-full aspect-auto"><BarChart data={chartData} margin={{ top: 12, right: 10, left: -12, bottom: 4 }}><CartesianGrid vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} interval={0} tick={{ fontSize: 10 }} /><YAxis tickLine={false} axisLine={false} tickFormatter={value => `${value}일`} /><ReferenceLine y={0} stroke="#94a3b8" /><ChartTooltip content={<ChartTooltipContent labelKey="label" formatter={value => <span className="font-mono font-semibold">{Number(value) < 0 ? `${Math.abs(Number(value))}일 초과` : `D-${value}`}</span>} />} /><Bar dataKey="daysRemaining" radius={[5, 5, 0, 0]}>{chartData.map(item => <Cell key={item.id} fill={statusColor[item.status]} />)}</Bar></BarChart></ChartContainer> : <p className="rounded-xl border border-dashed bg-muted/30 px-5 py-16 text-center text-sm text-muted-foreground">최근 제조일이 입력된 관리 제품이 있으면 잔여일수 차트가 표시됩니다.</p>}<div className="mt-3 flex flex-wrap gap-2 text-xs"><Badge className="border-red-200 bg-red-50 text-red-700" variant="outline">기간 초과</Badge><Badge className="border-amber-200 bg-amber-50 text-amber-700" variant="outline">사전 알림</Badge><Badge className="border-emerald-200 bg-emerald-50 text-emerald-700" variant="outline">여유 있음</Badge>{excludedCount ? <span className="ml-auto text-muted-foreground">중단·중지·입력 대기 제외 {excludedCount}건</span> : null}</div></CardContent></Card>
      <Card className="border-border/80 shadow-sm"><CardHeader className="border-b bg-card"><div className="flex items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-lg"><CalendarDays className="h-5 w-5 text-primary" />월간 검사 일정</CardTitle><CardDescription>마감일을 선택하면 해당 날짜의 검사 제품과 성적서를 확인합니다.</CardDescription></div><Button size="sm" variant="outline" className="shrink-0 gap-1.5" onClick={onGenerateMonthlyReport}><FileText className="h-4 w-4" />월간 PDF</Button></div></CardHeader><CardContent className="p-4 sm:p-5"><Calendar mode="single" selected={selectedDate} onSelect={date => { setSelectedDate(date); setDetailOpen(Boolean(date && (dateGroups.get(dateKey(date)) ?? []).length)); }} className="mx-auto rounded-xl border bg-white p-3" modifiers={datesByStatus} modifiersClassNames={{ overdue: "bg-red-100 text-red-800 font-bold hover:bg-red-200", urgent: "bg-amber-100 text-amber-800 font-bold hover:bg-amber-200", safe: "bg-emerald-100 text-emerald-800 font-semibold hover:bg-emerald-200" }} /><div className="mt-4 rounded-xl bg-muted/45 p-3"><p className="text-xs font-bold text-muted-foreground">{selectedDate ? `${dateText(dateKey(selectedDate))} 마감 일정` : "날짜를 선택하세요"}</p>{selectedItems.length ? <div className="mt-2 space-y-2">{selectedItems.map(item => <div key={item.id} className="flex items-center justify-between gap-2 rounded-lg bg-background px-2.5 py-2"><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.name}</p><p className="text-[11px] text-muted-foreground">{item.parentTypeName ?? "식품유형 미지정"} · {item.intervalMonths}개월</p></div><Badge variant="outline" className={statusBadgeClass(item.status)}>{dDayText(item.daysRemaining)}</Badge></div>)}</div> : <p className="mt-2 text-xs text-muted-foreground">이 날짜에 예정된 제품별 검사 마감이 없습니다.</p>}</div></CardContent></Card>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <Card className="border-border/80 shadow-sm"><CardHeader><CardTitle className="text-base">만료 임박 구간별 현황</CardTitle><CardDescription>향후 검사 대응 우선순위를 구간별로 확인합니다.</CardDescription></CardHeader><CardContent>{riskBuckets.some(item => item.count) ? <ChartContainer config={{ count: { label: "제품 수", color: "#0f766e" } }} className="h-[235px] w-full aspect-auto"><BarChart data={riskBuckets} margin={{ top: 8, right: 8, left: -18, bottom: 0 }}><CartesianGrid vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fontSize: 11 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip formatter={value => [`${value}건`, "제품 수"]} /><Bar dataKey="count" radius={[5, 5, 0, 0]}>{riskBuckets.map(item => <Cell key={item.label} fill={item.color} />)}</Bar></BarChart></ChartContainer> : <p className="rounded-xl border border-dashed bg-muted/30 px-5 py-16 text-center text-sm text-muted-foreground">최근 제조일을 입력한 제품이 있으면 구간별 현황이 표시됩니다.</p>}</CardContent></Card>
      <Card className="border-border/80 shadow-sm"><CardHeader><CardTitle className="text-base">식품유형별 만료 임박 분포</CardTitle><CardDescription>기간 초과·7일 이내·30일 이내 제품을 유형별로 비교합니다.</CardDescription></CardHeader><CardContent>{expirationStats.typeDistribution.length ? <ChartContainer config={riskChartConfig} className="h-[235px] w-full aspect-auto"><BarChart data={expirationStats.typeDistribution} layout="vertical" margin={{ top: 4, right: 8, left: 8, bottom: 0 }}><CartesianGrid horizontal={false} /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey="typeName" width={85} tick={{ fontSize: 11 }} /><Tooltip /><Legend iconSize={9} wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="overdue" stackId="risk" fill="#dc2626" radius={[0, 3, 3, 0]} /><Bar dataKey="critical" stackId="risk" fill="#d97706" /><Bar dataKey="upcoming" stackId="risk" fill="#0f766e" /></BarChart></ChartContainer> : <p className="rounded-xl border border-dashed bg-muted/30 px-5 py-16 text-center text-sm text-muted-foreground">30일 이내 마감 제품이 있으면 유형별 분포가 표시됩니다.</p>}</CardContent></Card>
    </div>
    <Card className="border-border/80 shadow-sm"><CardHeader><CardTitle className="text-base">향후 30일 검사 마감 추이</CardTitle><CardDescription>오늘부터 30일 동안 제품별 검사 마감이 몰린 시점을 확인합니다.</CardDescription></CardHeader><CardContent><ChartContainer config={{ count: { label: "마감 제품 수", color: "#0f766e" } }} className="h-[220px] w-full aspect-auto"><LineChart data={expirationStats.trend} margin={{ top: 10, right: 12, left: -18, bottom: 0 }}><CartesianGrid vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} interval={0} tick={{ fontSize: 10 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip formatter={value => [`${value}건`, "마감 제품 수"]} labelFormatter={(_, payload) => payload?.[0]?.payload?.day === 0 ? "오늘" : `D+${payload?.[0]?.payload?.day ?? ""}`} /><Line type="monotone" dataKey="count" stroke="#0f766e" strokeWidth={3} dot={{ r: 3, fill: "#0f766e" }} activeDot={{ r: 5 }} /></LineChart></ChartContainer></CardContent></Card>
    <Dialog open={detailOpen} onOpenChange={setDetailOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{selectedDate ? `${dateText(dateKey(selectedDate))} 검사 마감 상세` : "검사 마감 상세"}</DialogTitle><DialogDescription>선택한 날짜에 마감되는 제품별 일정과 등록된 검사성적서입니다.</DialogDescription></DialogHeader><div className="max-h-[58vh] space-y-3 overflow-y-auto pr-1">{selectedItems.map(item => { const productCertificates = certificatesByProduct.get(item.id) ?? []; return <div key={item.id} className="rounded-xl border bg-muted/25 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.parentTypeName ?? "식품유형 미지정"} · {item.intervalMonths}개월 · {item.nextDeadline}</p></div><Badge variant="outline" className={statusBadgeClass(item.status)}>{dDayText(item.daysRemaining)}</Badge></div>{productCertificates.length ? <div className="mt-3 space-y-2">{productCertificates.map(certificate => <div key={certificate.id} className="flex items-center justify-between gap-2 rounded-lg bg-background p-2"><div className="min-w-0"><p className="truncate text-xs font-medium">{certificate.fileName}</p><p className="text-[11px] text-muted-foreground">검사일 {certificate.inspectionDate ?? "미입력"}</p></div><Button size="sm" variant="outline" className="shrink-0 gap-1" asChild><a href={certificate.downloadUrl}><FileDown className="h-3.5 w-3.5" />성적서</a></Button></div>)}</div> : <p className="mt-3 text-xs text-muted-foreground">등록된 검사성적서가 없습니다.</p>}</div>; })}</div></DialogContent></Dialog>
  </section>;
}
